/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m1.piu;

import java.awt.BorderLayout;
import java.net.URL;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.fxml.FXMLLoader;
import javafx.fxml.JavaFXBuilderFactory;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.Pane;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Exceptions;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//m1.piu//Contacts//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "ContactsTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "m1.piu.ContactsTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ContactsAction",
        preferredID = "ContactsTopComponent"
)
@Messages({
    "CTL_ContactsAction=Contacts",
    "CTL_ContactsTopComponent=Contacts Window",
    "HINT_ContactsTopComponent=This is a Contacts window"
})
public final class ContactsTopComponent extends TopComponent {

    private static JFXPanel jfxPanel;
    private static GridPane gridPane;
    //private MyFXController controller;
    
    public ContactsTopComponent() {
        initComponents();
        setName(Bundle.CTL_ContactsTopComponent());
        setToolTipText(Bundle.HINT_ContactsTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);

        setLayout(new BorderLayout());
        init();
    }
    
    private void init() {
        jfxPanel = new JFXPanel(); //WizPanelController(); //return new JFXPanel controller
        
        Platform.setImplicitExit(false);
        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                createScene();  //standard Swing Interop Pattern
            }
        });
        
        add(jfxPanel);
    }
    
    private void createScene() {
        try {
            gridPane = new GridPane();

            URL location1 = getClass().getResource("fxml/contactsList.fxml");
            FXMLLoader fxmlLoader1 = new FXMLLoader();
            fxmlLoader1.setLocation(location1);
            fxmlLoader1.setBuilderFactory(new JavaFXBuilderFactory());
            Parent root1 = (Parent) fxmlLoader1.load(location1.openStream());
            gridPane.add(root1, 0, 0);
            
            URL location2 = getClass().getResource("fxml/contactDetails.fxml");
            FXMLLoader fxmlLoader2 = new FXMLLoader();
            fxmlLoader2.setLocation(location2);
            fxmlLoader2.setBuilderFactory(new JavaFXBuilderFactory());
            Parent root2 = (Parent) fxmlLoader2.load(location2.openStream());
            gridPane.add(root2, 0, 1);
            
            Scene scene = new Scene(gridPane);
            jfxPanel.setScene(scene);
            
            //controller = (MyFXController) fxmlLoader.getController();
        }
        catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
